version: "3.9"
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    environment: 
      - MYSQL_ROOT_PASSWORD=p@$$w0rd
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=passw0rd
    ports: 
      - 3306:3306
  wordpress:
    build: .
    restart: always
    ports:
      - 9000:80
    depends_on: 
      - database

        


