name: Push docker image
on: [push]
jobs:
  Push-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Log in to Docker Hub
        uses: actions/checkout@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PW }}
      - name: 🐳 Build and publish docker image to docker hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: weblwabl/nginx_wp:latest
      - run: echo "This job's status is ${{ job.status }}."